### ISSUE TITLE
GitHub merge commits are not signed

### ISSUE THREAD

**Issue by creideiki** [saab-simc-admin/palletjack#16]
When a pull request is accepted, GitHub generates a merge commit. However, since GitHub does not have your private GnuPG key, it cannot sign this merge commit.

Should we accept this as a fact of life when doing development on GitHub, or should we force everyone not to use the web interface but instead do all the merging locally? There is documentation on how to do it on every pull request page, so it's not hard as such, it's _just_ a social problem.

**Comment by notCalle** [comment]
Doh! That's bad. The complete chain should be signed.

**Comment by creideiki** [comment]
This looks to be fixed now, after we rebased and resigned EVERYTHING.

In the future, don't use GitHub merging; pull the changes down and merge locally.
