### ISSUE TITLE
Allow hierarchical names

### ISSUE THREAD

**Issue by creideiki** [saab-simc-admin/palletjack#23]
Currently, directories in a warehouse have rigidly defined semantics: `<type>/<object name>/`. This is a bit restrictive, since it makes it impossible to have e.g. `service/dhcp-server/lab-network/`, which we probably want. We probably still want the first level to be a type and the entire rest of the path to be collected into an object name.

**Comment by notCalle** [comment]
Consider the following structure:

```
service/
   dhcp-server/
      common-config.yaml
      lab-network/
         specific-config.yaml
```

`dhcp-server/lab-network` should have an implicitly generated `_parent` -> `dhcp-server` inheritance link in the resulting PalletJack DAG.

Hierarchical names should not be restricted to just two levels, but generalized to any depth.
