### ISSUE TITLE
Need DHCP option 15: domain-name

### ISSUE THREAD

**Issue by notCalle** [saab-simc-admin/palletjack#47]
palletjack2kea needs to generate config that sends DHCP option 15: domain-name, so that DHCP clients know how to look up short names.

**Comment by creideiki** [comment]
Code written, waiting for #52.

**Comment by creideiki** [comment]
_sigh_ [Kea 1.1.0 introduced the ability to specify options on a per host basis.](http://kea.isc.org/docs/kea-guide.html#reservation4-options)

```
# rpm -q kea
kea-1.0.0-9.el7.x86_64
```

**Comment by creideiki** [comment]
Tried the generated configuration with a hand-built Kea 1.1.0-beta. The configuration loads, and according to `tcpdump` the server sends option 15 Domain-Name. However, it does not send the Hostname option, and Anaconda thinks it's called `localhost.localdomain`.

**Comment by creideiki** [comment]
Not a problem with this code: #54.

**Comment by notCalle** [comment]
Reopened due to killed pull request merge.

**Comment by creideiki** [comment]
For now, we're OK with sending the same boot-file to everyone, since we can chain load Solaris from PXELINUX, and every machine wants the same domain name anyway. This means we can survive using Kea 1.0.0.
