### ISSUE TITLE
Rewrite palletjack2* to use KVDAG relations

### ISSUE THREAD

**Issue by notCalle** [saab-simc-admin/palletjack#51]
palletjack2\* tools currently search the whole DAG for children of a specific type.
Reimplement to use underlying KVDAG methods to find children, and then search just their children for specifics.

**Comment by creideiki** [comment]
Code written in [creideiki:parents-and-children](https://github.com/creideiki/palletjack/tree/parents-and-children), but not submitted since I don't have my signing key on me.
