### ISSUE TITLE
Improve child traversal code

### ISSUE THREAD

**Issue by creideiki** [saab-simc-admin/palletjack#75]
Currently, we loop over all children of a specific type by doing ugly and repetitive things like:

``` yaml
system.children.each do |interface|
  next unless interface.kind == 'ipv4_interface'
  dostuff(interface)
end
```

It should be closer to

``` yaml
system.children('ipv4_interface') { |interface|
  dostuff(interface)
}
```

Implement a helper method in the `Pallet` class to do this.

**Comment by notCalle** [comment]
This has been generalized and implemented in KVDAG instead, for future profit.

**Comment by creideiki** [comment]
No, that did not close the issue. That implemented the underlying functionality needed to implement the solution to the issue.
